[package]
name = "k_panic_handler"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib", "rlib"]
test = false
doctest = false
bench = false
