[package]
name = "k_corelib"
version = "0.1.0"
edition = "2024"

[dependencies]
boot_info = { path = "../boot_info" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type=["staticlib", "rlib"]
test = false
doctest = false
bench = false